function menuBarGenerator(){
  var menu = document.getElementById('menuBar');
  var html = '';
  html += '  <!-- Navigation -->';
  html += '  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">';
  html += '      <div class="container">';
  html += '          <!-- Brand and toggle get grouped for better mobile display -->';
  html += '          <div class="navbar-header">';
  html += '                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">';
  html += '                    <span class="sr-only">Toggle navigation</span>';
  html += '                    <span class="icon-bar"></span>';
  html += '                    <span class="icon-bar"></span>';
  html += '                    <span class="icon-bar"></span>';
  html += '                    <span class="icon-bar"></span>';
  html += '                </button>';
  html += '                <a class="navbar-brand" href="index.html">Cybersecurity @ MIT</a>';
  html += '            </div>';
  html += '            <!-- Collect the nav links, forms, and other content for toggling -->';
  html += '            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">';
  html += '                <ul class="nav navbar-nav">';
  html += '                    <li>';
  html += '                        <a href="2018.html">2018</a>';
  html += '                    </li>';
  html += '                    <li>';
  html += '                        <a href="2017.html">2017</a>';
  html += '                    </li>';
  html += '                    <li>';
  html += '                        <a href="2016.html">2016</a>';
  html += '                    </li>';
  html += '                    <li>';
  html += '                        <a href="about.html">About</a>';
  html += '                    </li>';
  html += '                    <li>';
  html += '                        <a href="http://geospatial.mit.edu">Research</a>';
  html += '                    </li>';
  html += '                    <li>';
  html += '                        <a href="mailto:software@mit.edu">Contact</a>';
  html += '                    </li>';
  html += '                </ul>';
  html += '            </div>';
  html += '            <!-- /.navbar-collapse -->';
  html += '        </div>';
  html += '        <!-- /.container -->';
  html += '    </nav>';  
  menu.innerHTML = html;
}